version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build --prefix client
      - cp -r client/build/* server/  # Copy the build files into server directory
      - cd server
      - zip -r ../server.zip *  # Zip everything inside the server directory

artifacts:
  files:
    - server.zip
